//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dada
    {
        public int id { get; set; }
        public int alumneid { get; set; }
        public int assignaturaid { get; set; }
        public int professorid { get; set; }
    
        public virtual alumne alumne { get; set; }
        public virtual assignatura assignatura { get; set; }
        public virtual profe profe { get; set; }
    }
}
